repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--ini, .bandit,-ll, --recursive, .]
        files: .py$

- repo: local
  hooks:
  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
    exclude: setup.py


  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pytest -v
    types: [python]
    verbose: true
    pass_filenames: false
    always_run: true

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: pytest --cov --cov-fail-under=100
    types: [python]
    pass_filenames: false
    exclude: setup.py
